"""ANL 2026 participant team_21584 (agent id 21584, class MajiKayo).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .examples.myway import MajiKayo as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21584
NAME = 'MajiKayo'
CLASS_NAME = 'MajiKayo'
VERSION = '0.78.83'
TEAM = 'Team 344'
AUTHOR = 'Kota Fujimoto'
MEMBERS = [{'name': 'Kota Fujimoto', 'institution': 'Aichi', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Aichi'
TAGS = []
USES_LLM = False
DESC = 'MajiKayoAgent is a negotiation agent based on a real-utility concession strategy combined with opponent modeling. It starts by proposing its own best outcome\r\n  twice, then continues with unused outcomes in descending order of its true utility while staying above its reservation value. After the early phase, it\r\n  considers a small lookahead set of high-utility candidates and chooses the one estimated to be most favorable to the opponent. Its acceptance rule compares the\r\n  opponent’s offer with the utility of the agent’s next planned self-offer, accepting only when the received offer is at least as good. This design aims to\r\n  maintain strong self-utility while improving agreement chances through opponent-aware offer selection.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
