"""ANL 2026 participant team_21600 (agent id 21600, class AgentTokyoV11).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent_tokyo_v11 import AgentTokyoV11 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21600
NAME = 'TokyoV11'
CLASS_NAME = 'AgentTokyoV11'
VERSION = '0.54.73'
TEAM = 'Team 483'
AUTHOR = 'Kanika Pathak'
MEMBERS = [{'name': 'Kanika Pathak', 'institution': 'Crif', 'country': 'India'}]
COUNTRY = 'India'
INSTITUTION = 'Crif'
TAGS = ['Bayesian Methods', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
