"""ANL 2026 participant team_21043 (agent id 21043, class Agent360).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent360 import Agent360 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21043
NAME = 'Agent360'
CLASS_NAME = 'Agent360'
VERSION = '4.2.1'
TEAM = 'Team 360'
AUTHOR = 'Noam Kazum'
MEMBERS = [{'name': 'Noam Kazum', 'institution': 'College of Management Academic Studies', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'College of Management Academic Studies'
TAGS = ['Game Theory', 'Psychology', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'Agent360 is a bilateral negotiator whose design follows a concealment-first principle: early offers deliberately misrepresent issue priorities so that frequency-based opponent learners infer an incorrect utility function. At the same time, later phases and acceptance rules extract profitable agreements. The agent uses no oracle access to the opponent’s class or true utility–only observed offers, negotiation seat, and the relative deadline time. The bidding personas are related to theories of signaling, strategic misrepresentation, and the limits of honesty in non-cooperative negotiation.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
