"""ANL 2026 participant team_21639 (agent id 21639, class AgentNexus).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agentnexus import AgentNexus as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21639
NAME = 'AgentNexus_2.0'
CLASS_NAME = 'AgentNexus'
VERSION = '0.87.44'
TEAM = 'Team 407'
AUTHOR = 'Nishanth Rajan'
MEMBERS = [{'name': 'Nishanth Rajan', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'AgentNexus is a robust BOA-based ANL 2026 negotiator focused on high utility, opponent adaptation, and preference concealment. It uses a Boulware-style concession curve, frequency-based opponent modeling, and privacy-aware bid selection to avoid repeatedly revealing its strongest issue values. Offers are chosen from high-utility candidate bands while considering estimated opponent acceptance, Pareto balance, novelty, and late-deadline safety. Acceptance is conservative early, compares incoming offers against planned future bids, and relaxes near the deadline to avoid unnecessary failures. The agent keeps all learning strictly within a single negotiation, uses no external memory, and remains scenario-general and deterministic enough for reliable tournament behavior.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
