"""ANL 2026 participant team_21762 (agent id 21762, class BetterCallAgentInfinityV1000).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .better_call_agent_infinity_v1000 import BetterCallAgentInfinityV1000 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21762
NAME = 'BetterCallAgentInfinityV1000'
CLASS_NAME = 'BetterCallAgentInfinityV1000'
VERSION = '1'
TEAM = 'BetterCallAgent'
AUTHOR = 'Steffan Wolter'
MEMBERS = [{'name': 'Steffan Wolter', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Johny Tarbouch', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Qasim Sefaldeen', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Game Theory', 'Heuristic / Rule-based']
USES_LLM = False
DESC = "BetterCallAgentInfinity V1000 is a time-based concession negotiator for the ANL 2026 concealing challenge. It holds high utility early and concedes along a Boulware-style aspiration curve toward a Nash-bargaining floor estimated against an online opponent model, reaching agreements without giving away value. A Hard-Headed frequency model estimates the opponent's preference ranking from their offers (value frequencies and unchanged issues) and is published for the concealing score. Among utility-acceptable outcomes it picks offers that minimise the correlation between its own offer frequencies and its true utility, concealing its preferences from frequency-based opponent models. A late safety net secures positive-advantage deals near the deadline."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
