"""ANL 2026 participant team_21369 (agent id 21369, class LionelWei).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .lionelwei_agent import LionelWei as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21369
NAME = 'LIonel'
CLASS_NAME = 'LionelWei'
VERSION = '0.26.49'
TEAM = 'Team 423'
AUTHOR = 'wei'
MEMBERS = []
COUNTRY = 'China'
INSTITUTION = 'Nanjing University of Science and Technology'
TAGS = ['Bayesian Methods', 'Game Theory', 'Heuristic / Rule-based', 'Optimization', 'Evolutionary / Genetic']
USES_LLM = False
DESC = 'LionelNeg combines a time-based constrained Boulware concession schedule with an adaptive multi-criteria offer scorer. The scorer integrates self-utility normalization, a dual-signal opponent model (concession slope and cumulative magnitude), Pareto frontier approximation, and a variance-based frequency-holder detector that classifies opponents into three behavioral archetypes: hardliners (Boulware, Tough), frequency holders that hold then concede late (BOA, MAP), and active conceding opponents (Conceder, NaiveTFT, CAB). Each archetype triggers a distinct scoring regime, including dynamic hard-hold with patience-adaptive relaxation and one-sided Pareto locking for hardliners and frequency holders. Acceptance uses a monotonic downward-ratchet threshold. An adversarial tie-break (B2) minimizes preference-ranking leakage to improve the concealing score.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
