"""ANL 2026 participant team_21565 (agent id 21565, class Badiron).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .badiron import Badiron as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21565
NAME = 'BadIronV4'
CLASS_NAME = 'Badiron'
VERSION = '4'
TEAM = 'Team 408'
AUTHOR = 'Itamar Hassidim'
MEMBERS = [{'name': 'Itamar Hassidim', 'institution': 'Bar-Ilan University', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'Bar-Ilan University'
TAGS = ['Game Theory', 'Economics', 'Heuristic / Rule-based']
USES_LLM = False
DESC = "Badiron is a fixed-heuristic bilateral negotiator engineered for the ANL 2026 scoring rule, which rewards both individual advantage (deal utility above the reservation value) and the relative opponent-modelling/concealing contest. Concession & acceptance: a firm Boulware curve (exponent 12) holds demands near the maximum and concedes only in the final stretch, combined with an AC-next acceptance rule, immediate acceptance of near-optimal offers, and an endgame deal-securing sweep after 97% of the rounds. Opponent modelling: a model republished every turn as a LinearAdditive utility function, ranking each value by when it first appears in the opponent's offers (a conceding opponent reveals its preferred values first) and weighting issues by inverse entropy, to maximise the Kendall rank-correlation score. Pareto-frontier bidding: among the outcomes still acceptable to us, it offers the one the opponent is estimated to value most, keeping every concession efficient so deals close on terms favourable to us."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
