"""ANL 2026 participant team_21573 (agent id 21573, class DecepTon).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .decepton import DecepTon as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21573
NAME = 'DecepTor'
CLASS_NAME = 'DecepTon'
VERSION = '0.0.1'
TEAM = 'Team 493'
AUTHOR = 'MertAltintasOzu'
MEMBERS = [{'name': 'MertAltintasOzu', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Multi-Agent Reinforcement Learning', 'Supervised Learning', 'Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'Deceptive bilateral negotiation agent using utility-equivalent bid swaps, DANS-adaptive Boulware concession, GSmithFrequencyModel opponent modeling, and a composite four-condition acceptance strategy to maximize the ANL 2026 dual score (advantage + Kendall-tau deception).'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
