"""ANL 2026 participant team_21328 (agent id 21328, class MiyaDreamBeliefNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .miya_dreambelief_agent.agent import MiyaDreamBeliefNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21328
NAME = 'MiyaDreamBelief'
CLASS_NAME = 'MiyaDreamBeliefNegotiator'
VERSION = '0.7.0'
TEAM = 'Team 421'
AUTHOR = 'Miyashita Taisuke'
MEMBERS = [{'name': 'Miyashita Taisuke', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Deep Learning', 'Reinforcement Learning', 'Multi-Agent Reinforcement Learning', 'Supervised Learning', 'Bayesian Methods', 'Heuristic / Rule-based', 'Simulation / Monte Carlo', 'Transfer / Meta Learning']
USES_LLM = False
DESC = 'MiyaDreamBelief is a negotiation agent that combines a Dreamer-style learned policy with a safe heuristic fallback. The learned policy was trained in simulated ANL-style bilateral negotiations with randomized scenarios, opponent types, negotiation order, utility functions, reservation values, and self-play opponents. It uses opponent-belief features inspired by VariBAD, utility-table estimation, and opponent behavior reconstruction to adapt its offers and acceptance decisions. The agent estimates opponent preferences and exposes an opponent utility function when possible, while selecting offers based on its own utility target and estimated opponent utility. If the learned model cannot be loaded, the domain is outside the supported size, or a runtime error occurs, the agent falls back to a rule-based concession strategy with frequency-based opponent utility estimation.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
