"""ANL 2026 participant team_22271 (agent id 22271, class PerikosV3).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .perikos_v3 import PerikosV3 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22271
NAME = 'PerikosV3'
CLASS_NAME = 'PerikosV3'
VERSION = '3.0.1'
TEAM = 'Team 412'
AUTHOR = 'Kosuke Nakata'
MEMBERS = [{'name': 'Kosuke Nakata', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = "PerikosV3 is a bilateral automated negotiation agent designed for the ANL 2026 league. The agent combines utility-preserving bidding, lightweight opponent modeling, and preference-concealing offer selection. At the beginning of each negotiation, it ranks all rational outcomes above its reservation value and uses a time-dependent aspiration threshold to protect high self-utility. From the opponent's offers, PerikosV3 incrementally estimates issue-value preferences using both long-term frequencies and decayed recent frequencies, while issue salience is inferred from value dispersion and counteroffer pressure. Candidate bids are selected by combining self-utility, estimated opponent utility, bid diversity, inertia toward promising received offers, and preference shielding. The acceptance strategy compares the received offer with the agent's planned counteroffer, allowing it to accept strong offers without unnecessary delay. This design aims to achieve high-utility agreements while reducing preference leakage and maintaining robust behavior across unknown opponents."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
