"""ANL 2026 participant team_21044 (agent id 21044, class EmEfAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .emef_agent import EmEfAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21044
NAME = 'EmEfAgent'
CLASS_NAME = 'EmEfAgent'
VERSION = '1.0.0'
TEAM = 'AgentInOzu'
AUTHOR = 'Emir ali Şahinoğulları'
MEMBERS = [{'name': 'Emir ali Şahinoğulları', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'EmEfAgent is a rule-based automated negotiation agent built for ANL 2026. It balances two goals simultaneously: maximizing agreement utility and concealing its true preferences from the opponent. It uses a Boulware-style bidding strategy, a frequency-based opponent model with entropy-weighted issue importance, and a conservative acceptance strategy combining reservation floors, ACNext logic, and Nash-product estimation. Occasionally, it places deliberately misleading bids on its most important issue to confuse frequency-based opponent models, while still keeping those bids above its utility floor.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
