"""ANL 2026 participant team_21350 (agent id 21350, class WhaleNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .whale import WhaleNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21350
NAME = 'WhaleV0.2'
CLASS_NAME = 'WhaleNegotiator'
VERSION = '0.0.2'
TEAM = 'Whales'
AUTHOR = 'Omri Perry'
MEMBERS = [{'name': 'Omri Perry', 'institution': 'Bar-Ilan University', 'country': 'Israel'}, {'name': 'Ori Braverman', 'institution': 'Bar-Ilan University', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'Bar-Ilan University'
TAGS = ['Supervised Learning', 'Game Theory', 'Economics', 'Psychology', 'Heuristic / Rule-based']
USES_LLM = False
DESC = "WhaleNegotiator is an advanced bilateral negotiation agent designed for the ANL 2026 competition. It features a modular architecture that combines dynamic opponent classification, adaptive bidding, and preference-concealing deception. At its core, the agent uses a Tactic Selector that classifies the opponent in real-time (e.g., Boulware, Conceder, Random, or Deceptive) and hot-swaps active bidders and acceptors. Bidding relies on a Nash-targeting concession curve (NashBidder) and step-based concession. Acceptance is governed by a strict, UOAgent-inspired acceptance curve and ACNext checks. The agent models the opponent's utility using an issue-frequency count (FrequencyModel) and includes deception detection to switch to a NullModel when facing preference poisoners. To hide its own preferences, WhaleNegotiator implements Dynamic Adaptive Deception (DAD) via an IssueDecoyDeceiver, which substitutes decoy values on high-impact issues within a time-decaying utility budget to confuse the opponent's model without risking final agreement convergence."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
