"""ANL 2026 participant team_21124 (agent id 21124, class IscasAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .iscas import IscasAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21124
NAME = 'IscasAgent'
CLASS_NAME = 'IscasAgent'
VERSION = '3.14.5'
TEAM = 'Team 391'
AUTHOR = 'Yize Li'
MEMBERS = [{'name': 'Yize Li', 'institution': 'University of Chinese Academy of Sciences  Institute of Software,Chinese Academy of Sciences', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'University of Chinese Academy of Sciences  Institute of Software,Chinese Academy of Sciences'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
