"""ANL 2026 participant team_22290 (agent id 22290, class SBDANL).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .sbdanl import SBDANL as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22290
NAME = 'SBDANL'
CLASS_NAME = 'SBDANL'
VERSION = '0.54.60'
TEAM = 'Team Ukku'
AUTHOR = 'Hajime Endo'
MEMBERS = [{'name': 'Hajime Endo', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = 'SBDANL — ANL 2026 (preference-concealing bilateral negotiator)\r\n\r\nSBDANL is a bilateral negotiator for the ANL 2026 "concealing preferences" challenge,\r\nbuilt on NegMAS (SAOCallNegotiator) with a Bidding–Opponent-model–Acceptance design.\r\n\r\n- Bidding: a strongly late-conceding Boulware target (e=20). Among rational outcomes\r\n  in a thin iso-utility band above the target it offers the one the opponent likes\r\n  most, so the value pattern of our offers is driven by the opponent, not by us.\r\n- Acceptance: accept any offer at or above the smooth Boulware base; a final-moment\r\n  clause (t>0.97) grabs any rational agreement, preventing no-agreement collapse.\r\n- Opponent model: a Smith-style frequency model (per-issue value frequencies with\r\n  early-offer recency, issue weights from value stability) published as\r\n  opponent_ufun so it earns the concealing share.\r\n\r\nKey insight behind the design: advantage and concealment are coupled, because utility\r\nis essentially determined by which issue-values one offers. Conceding walks down—and\r\nthus reveals—your preference ordering, while holding firm exposes only your single\r\nideal point. SBDANL therefore conceals mainly by NOT conceding (high Boulware) plus\r\nfree iso-utility selection, rather than by explicit obfuscation. It ranks first in a\r\nround-robin against all ANL 2026 sample agents and standard NegMAS baselines.\r\n\r\nDependencies: negmas (>=0.15.4). No state is stored between negotiations.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
