"""ANL 2026 participant team_21786 (agent id 21786, class AnchorNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .anchor import AnchorNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21786
NAME = 'Anchor'
CLASS_NAME = 'AnchorNegotiator'
VERSION = '1.86.54'
TEAM = 'Team 512'
AUTHOR = 'David Izhaki'
MEMBERS = [{'name': 'David Izhaki', 'institution': 'Bar-Ilan University', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'Bar-Ilan University'
TAGS = ['Game Theory', 'Economics', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = "Anchor is a single-class BOA (bidding, opponent-modelling, acceptance) negotiator designed around the ANL 2026 scoring rule. \r\nBecause the tournament ranks agents by their absolute mean score (Advantage plus a sharedConcealing point), Anchor maximises Advantage first: it opens near its ideal and holds a firm Boulware floor, so a firm opponent cannot drag it down to that opponent's ideal. It concedes only in a short end-game, to close a deal rather than time out with nothing. Among the offers worth at least its current target, it proposes the one most acceptable to the opponent, using a frequency opponent model that weights the opponent's early offers most heavily, since early offers reveal true preferences while late ones are concessions. Anchor emits this opponent estimate every round and treats deception as a last resort: we measured that distorting our own offers costs more Advantage than the shared Concealing point returns. It conceals by bidding firmly and modelling the opponent well, not by adding noise."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
