"""ANL 2026 participant team_21810 (agent id 21810, class Phantom8Negotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .phantom8_negotiator import Phantom8Negotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21810
NAME = 'Phantom8'
CLASS_NAME = 'Phantom8Negotiator'
VERSION = '0.36.80'
TEAM = 'Team 358'
AUTHOR = 'Jeremy Hui'
MEMBERS = [{'name': 'Jeremy Hui', 'institution': 'Rutgers University', 'country': 'United States'}]
COUNTRY = 'United States'
INSTITUTION = 'Rutgers University'
TAGS = ['Heuristic / Rule-based']
USES_LLM = False
DESC = 'This agent implements deception by using a phantom phase, where it selects least preferred outcomes to be offered which are also estimated to be poor for the opponent. This ensures that the decoy offers are typically rejected due to being low utility for both parties, but results in the opponent being unable to estimate our utilities. The agent also learns opponent preferences from frequency of observed offers to predict opponent utilities.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
