"""ANL 2026 participant team_21795 (agent id 21795, class NashtyNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .nashty import NashtyNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21795
NAME = 'Nashty Negotiator 12'
CLASS_NAME = 'NashtyNegotiator'
VERSION = '0.67.49'
TEAM = 'Nashty Negotiators'
AUTHOR = 'Lukas Knölker'
MEMBERS = [{'name': 'Lukas Knölker', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Kushtrim', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Austin Philip Paul', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Game Theory']
USES_LLM = False
DESC = "BS: Pick deal that's closest to 0.5 utility and offer that one for 90% of the game. After that concede in 10% buckets, where in each bucket the agent offers the deal that's the best for the opponent according to our OM. \r\nAS: Accept every deal above 0.75 during feint phase. AS_Next during concession phase. \r\nOM: Frequency model. (For further info check report)"
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
