"""ANL 2026 participant team_21589 (agent id 21589, class CunningMerchant).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .cunningmerchant import CunningMerchant as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21589
NAME = 'Cunning Merchant'
CLASS_NAME = 'CunningMerchant'
VERSION = '0.54.56'
TEAM = 'Team 485'
AUTHOR = 'Kaan Gonenli'
MEMBERS = [{'name': 'Kaan Gonenli', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'CunningMerchant is a bilateral negotiating agent designed for the ANL 2026 Deception challenge. It features an aggressive anchoring phase (first 15% of time), followed by a strict time-dependent Boulware concession curve (e=4.0) to maintain a tough posture. To maximize the Concealing score, it injects high-frequency utility vibrations (Haggling Fluctuation) and performs Active Preference Inversion on critical issues to dismantle the opponent\'s regression models. It tracks opponent concession rates via real-time linear regression and triggers a dynamic "Merchant Panic Mode" in the final 2.5% of rounds to guarantee valid agreements and eliminate timeout risks.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
