"""ANL 2026 participant team_22146 (agent id 22146, class StaBornNeg).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .staborn_negotiator import StaBornNeg as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22146
NAME = 'Staborn Negotiator'
CLASS_NAME = 'StaBornNeg'
VERSION = '0.38.14'
TEAM = 'Team 505'
AUTHOR = 'Athina Georgara'
MEMBERS = [{'name': 'Athina Georgara', 'institution': 'University of Southampton', 'country': 'United Kingdom'}]
COUNTRY = 'United Kingdom'
INSTITUTION = 'University of Southampton'
TAGS = []
USES_LLM = False
DESC = 'The "Staborn Negotiator" chooses one outcome that reaches ~75% of the maximum achievable utility, and keeps offering this outcome to the opponent. If the opponent counter-offers an outcome with better utility, the agent accepts; or if it is near the end (98% of relative time), the agent accepts any rational outcome.\r\nIn the meantime, the Staborn negotiator employs a frequency-based opponent modelling, i.e., keeps the frequency of visiting each value for all issues.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
