"""ANL 2026 participant team_21381 (agent id 21381, class ChangAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .chang_agent import ChangAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21381
NAME = 'ChangAgent'
CLASS_NAME = 'ChangAgent'
VERSION = '3.11.8'
TEAM = 'tnap'
AUTHOR = 'Shengbo Chang'
MEMBERS = [{'name': 'Shengbo Chang', 'institution': 'Tsinghua University', 'country': 'China'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Bayesian Methods', 'Optimization']
USES_LLM = False
DESC = 'ChangAgent is a negotiation agent designed for bilateral, multi-issue ANL negotiations. It combines a conservative dynamic bathtub bidding curve with online opponent modeling and bounded-regret acceptance. Its opponent model blends Smith-style frequency estimation, distribution-based frequency updates, and recency-sensitive transition signals to infer likely opponent preferences during a single negotiation. Bidding prioritizes high self-utility offers, previously unseen proposals, and opponent-seen anchors that may be acceptable, while adding controlled diversity to reduce preference leakage. Acceptance is strict early, cautious in the middle, and deadline-aware late, accepting worse offers only when expected future improvement is unlikely or too risky, for robust privacy-aware agreement seeking.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
