"""ANL 2026 participant team_20829 (agent id 20829, class Snake).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .snake_agent import Snake as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 20829
NAME = 'Snake'
CLASS_NAME = 'Snake'
VERSION = '3.11.8'
TEAM = 'Team 195'
AUTHOR = 'HIROTADA Matsumoto'
MEMBERS = [{'name': 'HIROTADA Matsumoto', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = "Snake is an adaptive negotiation agent designed for ANL2026. It combines opponent modeling, adaptive concession control, and Nash-product-based bid selection to dynamically adjust its strategy according to the opponent's behavior.\r\nThe agent estimates the opponent's preferences using a frequency-based model enhanced with entropy-based issue weight estimation, recent bidding trends, and transition patterns. Based on the observed concession behavior, it continuously estimates the opponent's concession style (e.g., hardliner or conceder) and adapts its own concession curve accordingly.\r\nFor bid generation, the agent first performs an information-concealing search by minimizing repeated offers while maintaining a target utility. In the later negotiation phase, it shifts to a Nash-product-based strategy over the estimated Pareto frontier to propose bids that are expected to maximize joint benefit.\r\nThe acceptance strategy combines a dynamic target utility with a deadline-aware policy to balance negotiation efficiency and agreement probability."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
