"""ANL 2026 participant team_20462 (agent id 20462, class OverlapConceder).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .overlap_conceder import OverlapConceder as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 20462
NAME = 'OverlapConceder'
CLASS_NAME = 'OverlapConceder'
VERSION = '0.0.1'
TEAM = 'Team 285'
AUTHOR = 'Ali Jahani'
MEMBERS = [{'name': 'Ali Jahani', 'institution': 'University of Tehran', 'country': 'Iran'}]
COUNTRY = 'Iran'
INSTITUTION = 'University of Tehran'
TAGS = ['Bayesian Methods', 'Optimization']
USES_LLM = False
DESC = "Using two time-varying utility bounds, the OverlapConceder adjusts its concessions based on exponents β_a and β_b and other variables. In order to estimate the opponent's utility through issue-match similarity, it constructs an opponent model from received offers, weighting older offers with a decay factor γ. An offer is accepted if it meets the lower bound or exceeds the opponent’s estimated utility by a threshold. When bidding, it looks for outcomes within the current target window that maximize the product of its own estimated utility and the opponent's estimated utility. It picks at random from the top k to find a balance between taking advantage of others and being unpredictable. Using a bayesian optimization method, we optimize for the hyper-parameters."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
