"""ANL 2026 participant team_21688 (agent id 21688, class BalanceOKNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .balanceok import BalanceOKNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21688
NAME = 'BalanceAgent'
CLASS_NAME = 'BalanceOKNegotiator'
VERSION = '0.86.17'
TEAM = 'CARC'
AUTHOR = 'Tianzi Ma'
MEMBERS = [{'name': 'Tianzi Ma', 'institution': 'Harbin Institute of Technology, Shenzhen', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'Harbin Institute of Technology, Shenzhen'
TAGS = ['Bayesian Methods', 'Psychology']
USES_LLM = False
DESC = 'BalanceAgent addresses the challenge of achieving high-utility agreements while reducing preference leakage in bilateral negotiation. It constructs a deceptive preference profile to diversify observable bidding signals, a balanced bidding strategy that keeps offer categories at comparable exposure frequencies, and a Bayesian opponent model that incorporates ordinal partial-order updates from observed rejection and counteroffer behavior.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
