"""ANL 2026 participant team_21676 (agent id 21676, class Hallucinators).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hallucinators import Hallucinators as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21676
NAME = 'HalucinatorAgent2026'
CLASS_NAME = 'Hallucinators'
VERSION = '0.61.40'
TEAM = 'Hallucinators'
AUTHOR = 'Gayathri Rajeev'
MEMBERS = [{'name': 'Gayathri Rajeev', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Diya Panikkassery Sudheer Kumar', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Kevin Antony', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Game Theory', 'Psychology', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'HalucinatorAgent is a BOA-style ANL negotiation agent using time-based offering, next-offer acceptance, frequency-based opponent modeling, adaptive concession control, preference masking, and late-stage rescue behavior. It estimates opponent preferences from offer distributions, protects high-value outcomes, and adjusts its strategy near the deadline to improve agreement chances while preserving strong own utility.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
