"""ANL 2026 participant team_21353 (agent id 21353, class HarrisonNeg).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .harrison_neg import HarrisonNeg as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21353
NAME = 'LoonyGryphon'
CLASS_NAME = 'HarrisonNeg'
VERSION = '3.11.8'
TEAM = 'Team 418'
AUTHOR = 'Harrison Oates'
MEMBERS = [{'name': 'Harrison Oates', 'institution': 'Australian National University', 'country': 'Australia'}]
COUNTRY = 'Australia'
INSTITUTION = 'Australian National University'
TAGS = []
USES_LLM = False
DESC = "ANL 2026 agent optimising Score = Advantage + Concealing.\r\n\r\n    Advantage: time-based linear concession with hard floor — never accept\r\n      below MIN_FRAC of our utility range above reserved value.\r\n\r\n    Concealing: issue-value frequency balancing. We track which values we have\r\n      offered for each issue and deliberately pick bids that use\r\n      underrepresented values. This keeps the opponent's frequency model flat\r\n      (close to uniform), minimising its Kendall-tau correlation with our\r\n      true utility function.\r\n\r\n    Opponent model: frequency-based with inverse-entropy issue weighting.\r\n      Issues where the opponent concentrates on few values (low entropy) are\r\n      presumed more important; we weight them higher. This improves our\r\n      Kendall-tau match with their true utility."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
