"""ANL 2026 participant team_21621 (agent id 21621, class AOA008).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .aoa import AOA008 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21621
NAME = 'AOA007'
CLASS_NAME = 'AOA008'
VERSION = '0.0.3'
TEAM = 'AOA007'
AUTHOR = 'Achiya Zigler'
MEMBERS = [{'name': 'Achiya Zigler', 'institution': 'Bar-Ilan University', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'Bar-Ilan University'
TAGS = ['Game Theory']
USES_LLM = False
DESC = 'Its a secret strategy! shhhhh'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
