"""ANL 2026 participant team_22257 (agent id 22257, class Anl).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hi.anl import Anl as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22257
NAME = 'ohanl'
CLASS_NAME = 'Anl'
VERSION = '0.20.23'
TEAM = 'チーム298'
AUTHOR = 'カズマ'
MEMBERS = [{'name': '望月和真', 'institution': None, 'country': None}, {'name': 'カズマ', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = "The Anl agent employs a mathematically rigorous, deterministic negotiation strategy designed for the ANAC 2026 competition, entirely eliminating the use of random variables for decision-making. It utilizes a three-phase adaptive Boulware approach to maximize individual payoff while systematically ensuring a high probability of agreement. In the initial phase (up to 40% of the negotiation time), the agent acts aggressively to explore the negotiation space, demanding near-maximum utility to carefully test the opponent's limits. During the second phase (40% to 85%), Anl dynamically models the opponent's preferences by calculating the exact similarity of proposed outcomes based on issue-matching frequencies. By continually tracking the opponent's concession rate using linear regression, it intelligently adjusts its own target utility to either exploit conceding behaviors or adapt to stubbornness. In the final phase (85% onwards), the agent shifts towards logical consensus-building to strictly avoid the risk of a complete negotiation breakdown. It strategically evaluates pre-calculated Pareto frontier candidates to find mutually acceptable outcomes that maximize the Nash bargaining product based on its precise utility estimations. Ultimately, Anl skillfully balances aggressive self-interest with cooperative mathematical adaptation, securing highly beneficial agreements well above its reservation value."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
