"""ANL 2026 participant team_21569 (agent id 21569, class GroupN).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .group_n import GroupN as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21569
NAME = 'GroupN'
CLASS_NAME = 'GroupN'
VERSION = '1.0.3'
TEAM = 'Team 492'
AUTHOR = 'cetinhosafci'
MEMBERS = [{'name': 'cetinhosafci', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Deep Learning', 'Multi-Agent Reinforcement Learning', 'Supervised Learning', 'Game Theory', 'Economics', 'Heuristic / Rule-based', 'Optimization', 'Simulation / Monte Carlo']
USES_LLM = False
DESC = 'DecepTor is a bilateral negotiating agent for ANL 2026 that employs \r\nthe BOA (Bidding, Opponent-modeling, Acceptance) architecture with three \r\nnovel contributions. First, a deception layer uses utility-equivalent bid \r\nswaps to strategically corrupt opponent preference models while maintaining \r\npersonal utility guarantees. Second, adaptive concession dynamically adjusts \r\nthe Boulware exponent based on opponent behavior classification via the DANS \r\nframework, enabling responsive negotiation strategies. Third, a composite \r\nfour-condition acceptance mechanism combines reservation guards, ACNext \r\nguarantees, Nash proximity checks, and opponent trend reversal detection to \r\nmaximize agreement probability while avoiding exploitation. The agent employs \r\ninverse-change-frequency weighted opponent modeling for robust preference \r\nestimation. Experimental validation demonstrates correct implementation with \r\nagreement rates exceeding 50% of maximum social welfare.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
