"""ANL 2026 participant team_21140 (agent id 21140, class TjAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .tjqzagent import TjAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21140
NAME = 'tjqzagent'
CLASS_NAME = 'TjAgent'
VERSION = '3.13.2'
TEAM = 'Team 395'
AUTHOR = 'TJQZ_Agent'
MEMBERS = [{'name': 'TJQZ_Agent', 'institution': 'Institute of Software, Chinese Academy of Sciences', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'Institute of Software, Chinese Academy of Sciences'
TAGS = ['Bayesian Methods', 'Game Theory', 'Search Algorithms', 'Simulation / Monte Carlo']
USES_LLM = False
DESC = "TjAgent is an automated bilateral negotiating agent designed for the ANL 2026 SAO protocol. \r\nIt combines a time-dependent concession curve with predictive opponent modeling to maximize joint \r\nutility while mitigating breakdown risks. \r\nThe core bidding mechanism utilizes an adaptive Boulware strategy modulated by a Softmax probability \r\ndistribution, which conceals the agent's true reservation value from predatory exploitation. During \r\nthe mid-to-late negotiation phases, a Conditional Pareto Filter prunes candidate bids to ensure mutual \r\nefficiency in large outcome spaces. \r\nConcurrently, the opponent modeling system tracks value distributions using Laplace frequency smoothing and deduces preference priorities through a Shannon Entropy-based weighting scheme, dynamically smoothed via an Exponential Moving Average (EMA). \r\nFinally, a robust, layered acceptance firewall handles edge cases by integrating exceptional utility thresholds, anticipatory future-target comparisons, micro-space corner guards, and automated stalemate floor decay rules to guarantee reliable and highly profitable agreements near absolute deadlines."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
