"""ANL 2026 participant team_21329 (agent id 21329, class AaNanteLucky).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .aa_nante_lucky import AaNanteLucky as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21329
NAME = 'AaNanteLucky'
CLASS_NAME = 'AaNanteLucky'
VERSION = '3.14.5'
TEAM = 'Team 376'
AUTHOR = 'Rinon Asanuma'
MEMBERS = [{'name': 'Rinon Asanuma', 'institution': None, 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Game Theory', 'Psychology', 'Search Algorithms', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'AaNanteLucky is a BOA-based ANL 2026 negotiating agent designed to achieve robust agreements while keeping its behavior simple and rule-compliant. Its offering strategy prioritizes high-utility outcomes, avoids excessive repetition, and uses opponent-model feedback cautiously near agreement-relevant situations. Its acceptance policy is conservative early and becomes more pragmatic near the deadline to reduce avoidable negotiation failures. For opponent modeling, the agent uses an in-memory frequency-based rank estimate built only from offers observed within the current negotiation, with conservative fallbacks when the observed history is sparse. The agent does not use persistent memory, file I/O, network access, or information from outside the current negotiation.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
