"""ANL 2026 participant team_21697 (agent id 21697, class Phantom8Negotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .phantom8_negotiator import Phantom8Negotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21697
NAME = 'phantom_etneg'
CLASS_NAME = 'Phantom8Negotiator'
VERSION = '0.39.48'
TEAM = 'Team 308'
AUTHOR = 'Xintong Wang'
MEMBERS = [{'name': 'Xintong Wang', 'institution': 'Rutgers University', 'country': 'United States'}]
COUNTRY = 'United States'
INSTITUTION = 'Rutgers University'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
