"""ANL 2026 participant team_21759 (agent id 21759, class CeanlNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .ceanl import CeanlNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21759
NAME = 'AdaptiveBathNegotiator'
CLASS_NAME = 'CeanlNegotiator'
VERSION = '0.94.39'
TEAM = 'Team 425'
AUTHOR = '尘'
MEMBERS = [{'name': '吕逸尘', 'institution': 'North China Electric Power University', 'country': 'China'}, {'name': '陈龙', 'institution': 'North China Electric Power University', 'country': 'China'}, {'name': '吴自高', 'institution': 'North China Electric Power University', 'country': 'China'}, {'name': '常昇博', 'institution': 'Tsinghua University', 'country': 'China'}, {'name': '尘', 'institution': 'North China Electric Power University', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'North China Electric Power University'
TAGS = ['Bayesian Methods', 'Game Theory', 'Economics', 'Heuristic / Rule-based', 'Simulation / Monte Carlo']
USES_LLM = False
DESC = 'AdaptiveBathNegotiator combines MiCRO-inspired descending aspiration with three-layer preference concealment. Its concession exponent adapts dynamically via real-time opponent trajectory classification into four types (Hardliner, Conceder, Erratic, Regular), with stalemate detection for deadlocked negotiations. Three synergistic mechanisms conceal private preferences: bluff bidding (low-utility proposals to mislead opponent models), target jitter (±5% random noise on aspiration targets), and novelty oscillation (alternating exploration and convergence weights). A self-utility-gated Tit-for-Tat mirror move and zero-sum scenario detection further enhance robustness. The agent ranks top-3 on the ANL 2026 leaderboard.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
