"""ANL 2026 participant team_21413 (agent id 21413, class OzuNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .ozu_negotiator import OzuNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21413
NAME = 'OzuNegotiator'
CLASS_NAME = 'OzuNegotiator'
VERSION = '0.48.8'
TEAM = 'Team 363'
AUTHOR = 'Umair Ahmad'
MEMBERS = [{'name': 'Umair Ahmad', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Bayesian Methods']
USES_LLM = False
DESC = 'OzuNegotiator demonstrates that combining an ultra stubborn aspiration curve with active deception mechanisms produces superior ANL 2026 scores compared to agents that model the opponent but make no effort to mislead it. The decoy issue trick, bounded deceptive randomization, and opponent-aware late bidding are complementary: deception raises the Concealing score while opponent-awareness raises the Advantage score.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
