"""ANL 2026 participant team_22139 (agent id 22139, class ErmanConcealNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .erman_conceal_negotiator import ErmanConcealNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22139
NAME = 'Erman Conceal Negotiator'
CLASS_NAME = 'ErmanConcealNegotiator'
VERSION = '0.82.8'
TEAM = 'Team 833'
AUTHOR = 'David Erman'
MEMBERS = [{'name': 'David Erman', 'institution': 'Bar-Ilan University', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'Bar-Ilan University'
TAGS = ['Heuristic / Rule-based']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
