"""ANL 2026 participant team_22289 (agent id 22289, class MirageV145).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .mirage_v145 import MirageV145 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22289
NAME = 'MirageV145'
CLASS_NAME = 'MirageV145'
VERSION = '0.72.98'
TEAM = 'Team 422'
AUTHOR = 'Avinash Pathak'
MEMBERS = [{'name': 'Avinash Pathak', 'institution': 'Independent', 'country': 'India'}]
COUNTRY = 'India'
INSTITUTION = 'Independent'
TAGS = ['Bayesian Methods', 'Game Theory', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'MirageV145 is a Nash-anchored hard-Boulware negotiator (β=64) with a Nash-bargaining utility floor that secures advantage by holding firm and conceding only near the deadline. It wins the concealment (τ) score on two fronts without altering its bidding: (i) it balances the value-frequencies it reveals so a frequency-modelling opponent cannot infer its preferences, and (ii) it reports a scenario-adaptive opponent model that infers competitive-vs-cooperative structure from observed offers and blends an online hard-headed frequency model with a matched prior. Stateless, single self-contained module, no disk/global state.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
