"""ANL 2026 participant team_21802 (agent id 21802, class AnlOmegaNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .anl_agent.entry import AnlOmegaNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21802
NAME = 'CodexAgentAnl'
CLASS_NAME = 'AnlOmegaNegotiator'
VERSION = '3.0.0'
TEAM = 'Team 507'
AUTHOR = 'Ryota GENSEKI'
MEMBERS = [{'name': 'Ryota GENSEKI', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Reinforcement Learning', 'Psychology']
USES_LLM = False
DESC = 'AnlOmegaNegotiator is a risk-safe hybrid bilateral negotiation agent designed for ANL 2026. It searches within time-dependent utility bands and ranks bids using self-utility, an adaptive frequency-based opponent model, Pareto and Nash guidance, reciprocity, diversity, and concealment penalties. The agent detects opponent concession, stubbornness, repetition, and deadlock, then adjusts candidate pools and endgame behavior without abandoning individual rationality. Every acceptance path rejects offers below the reservation value. Tiny single-issue domains receive a dedicated compromise rescue policy. During negotiation, a robust adaptive model guides bidding; after negotiation ends, an equal-issue Smith frequency model is reported to improve opponent-ranking accuracy without changing the bargaining trajectory. Cached frontier calculations, bounded candidate pools, and incremental history statistics keep execution practical in large domains.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
