"""ANL 2026 participant team_21728 (agent id 21728, class XGAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .xgnegotiator import XGAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21728
NAME = 'XGAgent'
CLASS_NAME = 'XGAgent'
VERSION = '0.74.36'
TEAM = 'Team 305'
AUTHOR = 'Fukutoku Yuma'
MEMBERS = [{'name': 'Fukutoku Yuma', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Supervised Learning']
USES_LLM = False
DESC = "The XGAgent is a sophisticated negotiator using XGBoost regression to dynamically model and predict its opponent's utility function. By transforming negotiation outcomes into feature vectors via\r\none-hot encoding, it treats negotiation as a regression problem. Its core intelligence lies in deceptive bidding. By monitoring incoming offers, the agent determines if a proposal is standard or a\r\ndeceptive move designed to manipulate perceptions. Through the PredictiveUfun class, it continuously updates its internal model based on the observed trajectory. Strategically, the agent does not merely\r\nreact; it actively probes opponent boundaries by issuing counter-offers that oscillate between maximizing utility and presenting tricky outcomes to elicit information about the opponent's true preference\r\nrange."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
